const data = [
  {
    id: 1,
    brand: "Peugeot",
    model: "301",
    fuel: "diesel",
    gear: "manuel",
    img: "https://www.ayintapotokiralama.com/wp-content/uploads/2024/02/Peugeot-301-Kiralamaa.png",
    insurance: "yok",
    year: "2017",
    info: "Ekonomik aile aracı, az yakar, çok kaçar.",
    price: "1500₺'den başlayan fiyatlarla.",
  },
  {
    id: 2,
    brand: "Citroen",
    model: "C-Elysee",
    fuel: "diesel",
    gear: "manuel",
    img: "https://ilkalternatif.com/wp-content/uploads/2020/03/citroen-c-elysee-736x414.jpg",
    insurance: "yok",
    year: "2017",
    info: "Ekonomik aile aracı, az yakar, çok kaçar.",
    price: "1750₺'den başlayan fiyatlarla.",
  },
  {
    id: 3,
    brand: "Citroen",
    model: "C-Elysee",
    fuel: "gasoline",
    gear: "manuel",
    img: "https://ilkalternatif.com/wp-content/uploads/2020/03/citroen-c-elysee-736x414.jpg",
    insurance: "var",
    year: "2020",
    info: "Ekonomik aile aracı, az yakar, çok kaçar.",
    price: "1750₺'den başlayan fiyatlarla.",
  },
  {
    id: 4,
    brand: "Fiat",
    model: "Egea",
    fuel: "diesel",
    gear: "manuel",
    img: "https://www.interportrentacar.com/tema/genel/uploads/araclar/fiat_megane.jpg",
    insurance: "var",
    year: "2020",
    info: "Ekonomik aile aracı, az yakar, çok kaçar.",
    price: "1750₺'den başlayan fiyatlarla.",
  },
  {
    id: 5,
    brand: "Fiat",
    model: "Fiorino",
    fuel: "diesel",
    gear: "manuel",
    img: "https://www.donanimhaber.com/cache-v2/?t=20230923203018&width=-1&text=0&path=https://www.donanimhaber.com/images/images/haber/169081/fiat-fiorino-nun-100-yil-ozel-seri-si-satisa-sunuldu169081_0.jpg",
    insurance: "var",
    year: "2020",
    info: "Ekonomik aile aracı, az yakar, çok kaçar.",
    price: "1500₺'den başlayan fiyatlarla.",
  },
  {
    id: 6,
    brand: "Fiat",
    model: "Fiorino",
    fuel: "diesel",
    gear: "manuel",
    img: "https://www.donanimhaber.com/cache-v2/?t=20230923203018&width=-1&text=0&path=https://www.donanimhaber.com/images/images/haber/169081/fiat-fiorino-nun-100-yil-ozel-seri-si-satisa-sunuldu169081_0.jpg",
    insurance: "yok",
    year: "2018",
    info: "Ekonomik aile aracı, az yakar, çok kaçar.",
    price: "1500₺'den başlayan fiyatlarla.",
  },
  {
    id: 7,
    brand: "Citroen",
    model: "C3",
    fuel: "diesel",
    gear: "manuel",
    img: "https://www.citroen.com.tr/content/dam/citroen/master/b2c/models/new-c3/visualizer/front-view/Citroen_C3_0MP00NWP_BlancBanquise_FR_1280_720.png",
    insurance: "var",
    year: "2017",
    info: "Ekonomik aile aracı, az yakar, çok kaçar.",
    price: "1750₺'den başlayan fiyatlarla.",
  },
  {
    id: 8,
    brand: "Kia",
    model: "Stonic",
    fuel: "gasoline",
    gear: "automatic",
    img: "https://www.bakfilo.com/wp-content/uploads/2024/07/35.png",
    insurance: "var",
    year: "2021",
    info: "Ekonomik aile aracı, az yakar, çok kaçar.",
    price: "2250₺'den başlayan fiyatlarla.",
  },
];

export default data;
